[package]
name = "malloc_size_of"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/servo/stylo"
edition = "2021"
publish = false

[features]
default = ["std", "void"]
std = []
void = ["dep:void"]

[dependencies]
void = { version = "1.0.2", optional = true }
